### ISSUE TITLE
Style/Card-Issue 

### ISSUE THREAD

**Issue by czhoffmann23** [ClementeSerrano/kosmos-ui#2]
Type of problem: **STYLE**

- Component name: **Card**
- What's the problem?: **Issue in border-shadow, it isn't seen clearly**
- Actual style: `    box-shadow: 0px 0px 7px 0px rgba(0,0,0,0), 0 3px 5px 0px rgba(0,0,0,0.03);`
- Example of problem (image, sections,component or steps):
![image](https://user-images.githubusercontent.com/37822767/84213416-94fe6780-aa8e-11ea-96db-3e68784a90b9.png)

**Comment by ClementeSerrano** [comment]
Deprecated. Already fixed.
